### ISSUE TITLE
Service error is raised if circuit contains a barrier instruction in the middle

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-transpiler#13]
The service will yield a `TranspilerError: 'Service error.'` if there is a barrier in the middle.

This circuit will work if the barrier is removed, but otherwise raises:

```python
def trivial_bvlike_circuit(N):
    """A trivial circuit that should boil down
    to just a X and Z gate since they commute out

    Parameters:
        N (int): Number of qubits

    Returns:
        QuantumCircuit: Output circuit
    """
    qc = QuantumCircuit(N)
    for kk in range(N - 1):
        qc.cx(kk, N - 1)
    qc.x(N - 1)
    qc.z(N - 2)
    qc.barrier()
    for kk in range(N - 2, -1, -1):
        qc.cx(kk, N - 1)
    return qc
```

**Comment by y4izus** [comment]
Thanks for reporting the issue @nonhermitian ! could you give more context about how are you running this code? I'm trying with `N=50` and `N=5` and I'm not able to reproduce it

**Comment by nonhermitian** [comment]
Sure,  this is the call.  The number of qubits does not seem to make a difference on my end.

```python

pm = TranspilerService(
    backend_name=backend.name,
    ai=True,
    optimization_level=2,
)

pm.run(qc)
```

**Comment by y4izus** [comment]
Thank you! I could reproduce it!
