### ISSUE TITLE
Rename this repo to qiskit-ibm-transpiler

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-transpiler#34]
As an effort to standardize the naming of all Qiskit client repos that communicate with IBM Quantum services, we decided to rename this to `qiskit-ibm-transpiler`. 

We need to ensure we maintain backward compatibility (e.g. `import qiskit_transpiler_service` would still work with a deprecation warning).

**Comment by cbjuan** [comment]
Confirming: the idea is to rename both the repository and the library, right?

**Comment by jyu00** [comment]
> Confirming: the idea is to rename both the repository and the library, right?

Yes. But as mentioned before, we need to keep backward compatibility during the deprecation period. What is your deprecation policy?

**Comment by y4izus** [comment]
When do you need this to be done @jyu00 ?

**Comment by jyu00** [comment]
The latest would be IEEE (Sept 15). But ideally it'd be done a couple of weeks before that so IEEE presenters have time to update their slides to use the new name.

**Comment by cbjuan** [comment]
> > Confirming: the idea is to rename both the repository and the library, right?
> 
> Yes. But as mentioned before, we need to keep backward compatibility during the deprecation period. What is your deprecation policy?

As of today we don't have any deprecation policy defined. We're working on it. One of the aspects we're discussing is that 3 months (as other Qiskit packages do) is too much given the current status of the project.

**Comment by Eric-Arellano** [comment]
Should we be renaming the URLs for docs? Right now we have:

qiskit-transpiler-service (Python)
qiskit-transpiler-service-rest

We can set up redirects if you want.

**Comment by jyu00** [comment]
@Eric-Arellano Redirect would be wonderful!

**Comment by Eric-Arellano** [comment]
> Redirect would be wonderful!

To be explicit, what are the new URLs for both APIs? Can you also please confirm them with Blake, given that these are hard to change and very user-facing?

**Comment by jyu00** [comment]
@Eric-Arellano you are talking about these 2 URLs, right? 
https://docs.quantum.ibm.com/api/qiskit-transpiler-service
https://docs.quantum.ibm.com/api/qiskit-transpiler-service-rest

Presumably they'd be renamed to match the new repo name, i.e. `qiskit-ibm-transpiler`. @blakejohnson do you have any objection? 

@cbjuan you probably already planned this, but the top level directory should also be renamed to `qiskit_ibm_transpiler` (but keep the old one), so one can do both
```python
from qiskit_ibm_transpiler import TranspilerService
from qiskit_transpiler_service import TranspilerService
```

**Comment by blakejohnson** [comment]
No objection from me, @jyu00

**Comment by jesus-talavera-ibm** [comment]
Published artifact: https://pypi.org/project/qiskit-ibm-transpiler/
Reopening because we still have to change maintainer from [ibm.q.widgets](https://pypi.org/user/ibm.q.widgets/) to [qiskit](https://pypi.org/user/qiskit/)

**Comment by y4izus** [comment]
This changes are already done:

- rename [repo](https://github.com/Qiskit/qiskit-ibm-transpiler)
- rename [library](https://pypi.org/project/qiskit-ibm-transpiler/) and [maintain the old one with a deprecation warning](https://pypi.org/project/qiskit-transpiler-service/)
- add qiskit as owner on pypi
- rename [docs](https://docs.quantum.ibm.com/api/qiskit-ibm-transpiler)
- redirect docs: https://docs.quantum.ibm.com/api/qiskit-transpiler-service


So I think we can close this issue. If anyone thinks something is missing, please, let me know. Otherwise, I will close this issue tomorror
