### ISSUE TITLE
Remove Python 3.8 test by October 2024

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-ibm-transpiler#9]
The end of life date for Python 3.8 is [2024-10](https://devguide.python.org/versions/#:~:text=2019%2D10%2D14-,2024%2D10,-%C5%81ukasz%20Langa), so by that date we should remove tests and code affected

**Comment by jesus-talavera-ibm** [comment]
Qiskit 1.3 will raise minimum version to 3.9: https://github.com/Qiskit/qiskit/releases/tag/1.3.0b1

**Comment by cbjuan** [comment]
Python 3.8 removed in our tests as part of our local mode feature release https://github.com/Qiskit/qiskit-ibm-transpiler/pull/125/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL42
